name: Bug Report
description: Report a bug or issue
title: "[Bug]: "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for reporting a bug.
        Please fill in the following items as detailed as possible.

  - type: textarea
    id: description
    attributes:
      label: Summary
      description: Please briefly describe the bug
      placeholder: What problem are you experiencing?
    validations:
      required: true

  - type: textarea
    id: reproduction
    attributes:
      label: Steps to Reproduce
      description: Please provide steps to reproduce the bug
      placeholder: |
        1. Execute '...'
        2. Call '...'
        3. Error occurs
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: Please describe how it should work
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: Please describe the actual behavior
    validations:
      required: true

  - type: textarea
    id: environment
    attributes:
      label: Environment
      description: Please provide your environment details
      placeholder: |
        - wikidot.py version:
        - Python version:
        - OS:
        - Execution environment: (Jupyter Notebook / script / etc.)
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Error Logs / Stack Trace
      description: Please paste any error messages or stack traces if available
      render: shell

  - type: textarea
    id: additional
    attributes:
      label: Additional Information
      description: Any other relevant information
